language: node_js
node_js: 10
dist: xenial
env:
  global:
    - npm_config_with_sdl_mixer=true
    - LS_NODE_GYP_OPTS="--jobs max"
cache:
  yarn: true
  directories:
    - ${HOME}/node_downloads

matrix:
  include:
    - name: "linux-x64 [Release]"
      os: linux
      env: npm_config_with_native_tests=true
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [gcc-6, g++-6, libegl1-mesa-dev, libgles2-mesa-dev, libsdl2-dev, libsdl2-mixer-dev]
      before_install:
        - set -e
        - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
      install: yarn --force
      script: skip
    - name: "darwin-x64 [Release]"
      os: osx
      env: npm_config_with_native_tests=true
      before_install:
        - set -e
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2 sdl2_mixer
      install: yarn --force
      script: yarn test
    - name: "linux-armv7l [Release]"
      os: linux
      env: npm_config_with_native_tests=false NODE_DOWNLOADS="${HOME}/node_downloads"
      addons:
        apt:
          packages: [patchelf]
      before_install:
        - set -e
        - mkdir -p ${NODE_DOWNLOADS}
        - git clone --depth 1 https://github.com/dananderson/crosstools.git ${HOME}/crosstools
        - . ${HOME}/.nvm/nvm.sh
      install:
        - nvm install v12.0.0
        - ./scripts/package-ls-node.sh linux-armv7l
      script: skip
