language: node_js
node_js:
  - "15.6.0"

dist: bionic
env:
  global:
    - npm_config_lse_install_opts="--jobs max"
    - NODE_DOWNLOADS="${HOME}/node_downloads"
    - LSE_CACHE="${HOME}/lse-cache"
    - CROSSTOOLS_HOME="${LSE_CACHE}/crosstools"
    - PATH="${LSE_CACHE}/upx:${PATH}"
    - ARTIFACTS_TARGET_PATHS="/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}"
cache:
  yarn: true
  directories:
    - ${HOME}/node_downloads
    - ${HOME}/lse-cache
    - ${HOME}/.nvm
matrix:
  include:
    - name: "windows-x64 [full-build]"
      os: windows
      env: YARN_GPG=no npm_config_lse_enable_native_tests=1
      before_install: set -e
      install: yarn --force
      script: yarn test
    - name: "windows-x64 [lse-node]"
      os: windows
      env: YARN_GPG=no
      before_install:
        - set -e
        - ./scripts/ci/lse-git-clone.sh "ci-packages"
        - choco install awscli
      install: skip
      script:
        - (cd scripts && yarn)
        - ./scripts/build-lse-node.js --sdl-profile dll --sdl-runtime-pkg "${LSE_CACHE}/ci-packages/SDL2-2.0.14-win32-x64.zip" --sdl-mixer-runtime-pkg "${LSE_CACHE}/ci-packages/SDL2_mixer-2.0.4-win32-x64.zip" --node-binary-cache "${NODE_DOWNLOADS}"
      after_success:
        - |
          if [ $TRAVIS_BRANCH == "master" ]; then
            export "PATH=/c/Program Files/Amazon/AWSCLIV2:$PATH"
            aws s3 cp build "s3://${ARTIFACTS_BUCKET}${ARTIFACTS_TARGET_PATHS}/build" --recursive || echo "Failed to upload to S3."
          fi
    - name: "darwin-x64 [full-build]"
      os: osx
      env: npm_config_lse_enable_native_tests=1
      install: yarn --force
      script:
        - (cd packages/@lse/core && yarn run cpplint)
        - yarn test
    - name: "darwin-x64 [lse-node]"
      os: osx
      before_install:
        - set -e
        - ./scripts/ci/lse-git-clone.sh "ci-packages"
      install:
        - set +e
        - (cd scripts && yarn) # XXX: travis hung here when yarn returned non-zero for a warning, unset -e to get output
        - set -e
        - ./scripts/build-lse-node.js --sdl-profile framework --sdl-runtime-pkg "${LSE_CACHE}/ci-packages/SDL2-2.0.14.framework.tar.gz" --sdl-mixer-runtime-pkg "${LSE_CACHE}/ci-packages/SDL2_mixer-2.0.4.framework.tar.gz" --node-binary-cache "$NODE_DOWNLOADS"
      script: skip
      addons:
        artifacts:
          branch: master
          paths:
            - $(ls build/*.tar.gz | tr "\n" ":")
