language: node_js
dist: xenial
env:
  global:
    - npm_config_ls_install_opts="--jobs max"
    - NODE_DOWNLOADS="${HOME}/node_downloads"
    - LSE_CACHE="${HOME}/lse-cache"
    - CROSSTOOLS_HOME="${LSE_CACHE}/crosstools"
    - PATH="${LSE_CACHE}/upx:${PATH}"
    - ARTIFACTS_TARGET_PATHS="/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}"
cache:
  yarn: true
  directories:
    - ${HOME}/node_downloads
    - ${HOME}/lse-cache
    - ${HOME}/.nvm
matrix:
  include:
    - name: "windows-x64 [full-build]"
      node_js: 14
      os: windows
      env: YARN_GPG=no npm_config_ls_enable_native_tests=1
      before_install:
        - set -e
        - ./scripts/ci/lse-git-clone.sh "ci-packages"
      install: yarn --force
      script:
        - ./scripts/build-lse-node.js --skip-compile --sdl-profile dll --sdl-runtime-pkg "${LSE_CACHE}/ci-packages/SDL2-2.0.12-win32-x64.zip" --sdl-mixer-runtime-pkg "${LSE_CACHE}/ci-packages/SDL2_mixer-2.0.4-win32-x64.zip" --node-binary-cache "${NODE_DOWNLOADS}"
      addons:
        artifacts:
          branch: master
          paths:
            - build/lse-node-v1.0.0-win-x64.zip
    - name: "linux-x64 [full-build]"
      os: linux
      env: npm_config_ls_enable_native_tests=1
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [gcc-6, g++-6]
        artifacts:
          branch: master
          paths:
            - $(ls build/npm/publishable/*.tgz | tr "\n" ":")
      before_install:
        - set -e
        - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
      install: yarn --force
      script:
        - (cd scripts && yarn)
        - ./scripts/create-npm-packages.sh --skip-yarn-install
    - name: "darwin-x64 [full-build]"
      os: osx
      env: npm_config_ls_enable_native_tests=1
      install: yarn --force
      script: yarn run lint
    - name: "darwin-x64 [lse-node]"
      os: osx
      before_install:
        - set -e
        - ./scripts/ci/lse-git-clone.sh "ci-packages"
      install:
        - set +e
        - (cd scripts && yarn) # XXX: travis hung here when yarn returned non-zero for a warning, unset -e to get output
        - set -e
        - ./scripts/build-lse-node.js --sdl-profile framework --sdl-runtime-pkg "${LSE_CACHE}/ci-packages/SDL2-2.0.12.framework.tar.gz" --sdl-mixer-runtime-pkg "${LSE_CACHE}/ci-packages/SDL2_mixer-2.0.4.framework.tar.gz" --node-binary-cache "$NODE_DOWNLOADS"
      script: skip
      addons:
        artifacts:
          branch: master
          paths:
            - $(ls build/*.tar.gz | tr "\n" ":")
    - name: "linux-armv7l [lse-node, lse-node-pi]"
      os: linux
      addons:
        apt:
          packages: [ patchelf ]
        artifacts:
          branch: master
          paths:
            - $(ls build/*.tar.gz | tr "\n" ":")
      before_install:
        - set -e
        - ./scripts/ci/lse-git-clone.sh "crosstools" "ci-packages"
        - ./scripts/ci/get-upx.sh
        - . ${CROSSTOOLS_HOME}/bin/x64-gcc-6.3.1.env
        - tar -xzf "${LSE_CACHE}/ci-packages/SDL2-2.0.12-armv7l-pi.tar.gz" --directory "${LSE_CACHE}"
      install:
        - (cd scripts && yarn)
        - ./scripts/build-lse-node.js --platform linux --arch armv7l --node-binary-cache "${NODE_DOWNLOADS}" --crosstools-home "${CROSSTOOLS_HOME}"
        - ./scripts/build-lse-node.js --skip-compile --platform linux --arch armv7l --profile pi --sdl-profile native --sdl-runtime-pkg "${LSE_CACHE}/SDL2-2.0.12-armv7l-pi" --compress-node-binary --strip-node-binary --minimal-node-install --node-binary-cache "${NODE_DOWNLOADS}" --crosstools-home "${CROSSTOOLS_HOME}"
      script: skip
    - name: "linux-armv6l [lse-node, lse-node-pi]"
      os: linux
      addons:
        apt:
          packages: [ patchelf ]
        artifacts:
          branch: master
          paths:
            - $(ls build/*.tar.gz | tr "\n" ":")
      before_install:
        - set -e
        - ./scripts/ci/lse-git-clone.sh "crosstools" "ci-packages"
        - ./scripts/ci/get-upx.sh
        - . ${CROSSTOOLS_HOME}/bin/x64-gcc-6.3.1.env
        - tar -xzf "${LSE_CACHE}/ci-packages/SDL2-2.0.12-armv6l-pi.tar.gz" --directory "${LSE_CACHE}"
      install:
        - (cd scripts && yarn)
        - ./scripts/build-lse-node.js --platform linux --arch armv6l --node-binary-cache "${NODE_DOWNLOADS}" --crosstools-home "${CROSSTOOLS_HOME}"
        - ./scripts/build-lse-node.js --skip-compile --platform linux --arch armv6l --profile pi --sdl-profile native --sdl-runtime-pkg "${LSE_CACHE}/SDL2-2.0.12-armv6l-pi" --compress-node-binary --strip-node-binary --minimal-node-install --node-binary-cache "${NODE_DOWNLOADS}" --crosstools-home "${CROSSTOOLS_HOME}"
      script: skip
