dist: xenial
sudo: required

language: node_js
node_js: 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libcec-dev
      - libsdl2-dev
      - libsdl2-mixer-dev

before_install:
  - . $HOME/.nvm/nvm.sh
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export npm_config_sdl_include_path=/usr/include/SDL2
  - export npm_config_sdl_library_path=/usr/lib/`gcc -dumpmachine`
  - export npm_config_with_sdl_mixer=true
  - export npm_config_with_cec=true
  - export npm_enable_native_tests=true
  - export npm_config_cec_include_path=/usr/include
  - export npm_config_cec_library_path=/usr/lib/`gcc -dumpmachine`
  - (cd packages/light-source && yarn link)
  - (cd packages/react-light-source && yarn link && yarn link light-source)
  - (cd packages/runtime && yarn link light-source && yarn link react-light-source)
  - (cd $HOME && git clone https://github.com/dananderson/crosstools.git)

install:
  - cd ${TRAVIS_BUILD_DIR}/packages/light-source
  - yarn
  - cd ${TRAVIS_BUILD_DIR}/packages/react-light-source
  - yarn
  - cd ${TRAVIS_BUILD_DIR}/packages/runtime
  - yarn --ignore-scripts

script:
  - cd ${TRAVIS_BUILD_DIR}/packages/light-source
  - yarn run prepublishOnly
  - cd ${TRAVIS_BUILD_DIR}/packages/react-light-source
  - yarn run prepublishOnly
  - cd ${TRAVIS_BUILD_DIR}/packages/runtime
  - yarn run lint
  - nvm install v10.16.3
  - nvm use v10.16.3
  - ./scripts/create-bundle linux-armv6l
  - nvm install v12.0.0
  - nvm use v12.0.0
  - ./scripts/create-bundle linux-armv7l

cache: yarn
