language: node_js
node_js: 14
dist: xenial
env:
  global:
    - npm_config_ls_with_sdl_mixer=true
    - npm_config_ls_install_opts="--jobs max"
    - LS_NODE_VERSION=v14.8.0
cache:
  yarn: true
  directories:
    - ${HOME}/node_downloads

matrix:
  include:
    - name: "linux-x64 [Release]"
      os: linux
      env: npm_config_ls_with_tests=true
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [gcc-6, g++-6, libegl1-mesa-dev, libgles2-mesa-dev, libsdl2-dev, libsdl2-mixer-dev]
      before_install:
        - set -e
        - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
      install: yarn --force
      script: skip
    - name: "darwin-x64 [Release]"
      os: osx
      env: npm_config_ls_with_tests=true
      before_install:
        - set -e
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2 sdl2_mixer
      install: yarn --force
      script: yarn run lint
    - name: "darwin-x64 [ls-node]"
      os: osx
      env: npm_config_ls_framework_path="$HOME/Frameworks"
      before_install:
        - git clone --depth 1 https://github.com/lightsourceengine/ci-packages.git "${HOME}/ci-packages"
        - mkdir -p "$HOME/Frameworks"
        - tar -xzf "${HOME}/ci-packages/SDL2-2.0.12.framework.tar.gz" --directory "$HOME/Frameworks"
        - tar -xzf "${HOME}/ci-packages/SDL2_mixer-2.0.4.framework.tar.gz" --directory "$HOME/Frameworks"
        - . ${HOME}/.nvm/nvm.sh
      install:
        - nvm install $LS_NODE_VERSION
        - cd scripts
        - yarn
        - sleep 10
        - cd ..
        - ./scripts/build-ls-node.js --framework-path "${npm_config_ls_framework_path}"
      script: skip
    - name: "linux-armv7l [Release]"
      os: linux
      env: npm_config_ls_with_tests=false NODE_DOWNLOADS="${HOME}/node_downloads"
      addons:
        apt:
          packages: [patchelf]
      before_install:
        - set -e
        - mkdir -p "${NODE_DOWNLOADS}"
        - git clone --depth 1 https://github.com/lightsourceengine/crosstools.git "${HOME}/crosstools"
        - . ${HOME}/.nvm/nvm.sh
      install:
        - nvm install $LS_NODE_VERSION
        - cd scripts
        - yarn
        - cd ..
        - ./scripts/build-ls-node.js linux-armv7l
      script: skip
  exclude:
    - name: "windows-x64 [Release]"
      os: windows
      env: YARN_GPG=no npm_config_ls_with_tests=true npm_config_ls_sdl_include="$HOME/SDL2-2.0.10/include" npm_config_ls_sdl_lib="$HOME/SDL2-2.0.10/lib/x64" npm_config_ls_sdl_mixer_include="$HOME/SDL2_mixer-2.0.4/include" npm_config_ls_sdl_mixer_lib="$HOME/SDL2_mixer-2.0.4/lib/x64"
      before_install:
        - set -e
        - git clone --depth 1 https://github.com/lightsourceengine/ci-packages.git "${HOME}/ci-packages"
        - powershell expand-archive -path "$HOME/ci-packages/SDL2/2.0.10/SDL2-devel-2.0.10-VC.zip" -destinationpath "$HOME"
        - powershell expand-archive -path "$HOME/ci-packages/SDL2_mixer/2.0.4/SDL2_mixer-devel-2.0.4-VC.zip" -destinationpath "$HOME"
      install: yarn --force
      script: skip
