dist: xenial
sudo: required

language: node_js
node_js: 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libcec-dev
      - libsdl2-dev
      - libsdl2-mixer-dev
      - patchelf

env:
  - NODE_DOWNLOADS=${HOME}/node_downloads
  - npm_config_with_native_tests=true
  - npm_config_with_sdl_mixer=true

before_install:
  - set -e
  - . ${HOME}/.nvm/nvm.sh
  - mkdir -p ${NODE_DOWNLOADS}
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - git clone --depth 1 https://github.com/dananderson/crosstools.git ${HOME}/crosstools

install:
  - yarn

script:
  - yarn test
  - nvm install v10.16.3
  - ./scripts/package-ls-node.sh linux-armv6l
  - nvm install v12.0.0
  - ./scripts/package-ls-node.sh linux-armv7l

cache:
  yarn: true
  directories:
    - ${HOME}/node_downloads
