/*
 * Copyright (C) 2019 Daniel Anderson
 *
 * This source code is licensed under the MIT license found in the LICENSE file in the root directory of this source tree.
 */

// Symbols used by internal classes for private/protected property access.

export const $adapter = Symbol.for('adapter')
export const $bind = Symbol.for('bind')
export const $unbind = Symbol.for('unbind')
export const $mappings = Symbol.for('mappings')
export const $scene = Symbol.for('scene')
export const $capture = Symbol.for('capture')
export const $bubble = Symbol.for('bubble')
export const $events = Symbol.for('events')
export const $width = Symbol.for('width')
export const $height = Symbol.for('height')
export const $fullscreen = Symbol.for('fullscreen')
export const $stage = Symbol.for('stage')
export const $root = Symbol.for('root')
export const $resource = Symbol.for('resource')
export const $destroy = Symbol.for('destroy')
export const $setActiveNode = Symbol.for('setActiveNode')
export const $displayIndex = Symbol.for('displayIndex')
export const $activeNode = Symbol.for('activeNode')
export const $destroying = Symbol.for('destroying')
export const $audioAdapter = Symbol.for('audioAdapter')
export const $mainLoopHandle = Symbol.for('mainLoopHandle')
export const $fps = Symbol.for('fps')
export const $attach = Symbol.for('attach')
export const $detach = Symbol.for('detach')
export const $frame = Symbol.for('frame')
export const $displays = Symbol.for('displays')
export const $exitListener = Symbol.for('exitListener')
export const $quitRequested = Symbol.for('quitRequested')
export const $input = Symbol.for('input')
export const $phase = Symbol.for('phase')
export const $type = Symbol.for('type')
export const $timestamp = Symbol.for('timestamp')
export const $key = Symbol.for('key')
export const $pressed = Symbol.for('pressed')
export const $repeat = Symbol.for('repeat')
export const $mapping = Symbol.for('mapping')
export const $source = Symbol.for('source')
export const $device = Symbol.for('device')
export const $connected = Symbol.for('connected')
export const $button = Symbol.for('button')
export const $axis = Symbol.for('axis')
export const $value = Symbol.for('value')
export const $cancelled = Symbol.for('cancelled')
export const $navigationManager = Symbol.for('navigationManager')
export const $hasFocus = Symbol.for('hasFocus')
