/*
 * Copyright (C) 2019 Daniel Anderson
 *
 * This source code is licensed under the MIT license found in the LICENSE file in the root directory of this source tree.
 */

// Symbols used by internal classes for private/protected property access.

const { for: symbolFor } = Symbol

export const $adapter = symbolFor('adapter')
export const $bind = symbolFor('bind')
export const $unbind = symbolFor('unbind')
export const $mappings = symbolFor('mappings')
export const $keyToDirectionMap = symbolFor('keyToDirectionMap')
export const $scene = symbolFor('scene')
export const $capture = symbolFor('capture')
export const $bubble = symbolFor('bubble')
export const $events = symbolFor('events')
export const $width = symbolFor('width')
export const $height = symbolFor('height')
export const $fullscreen = symbolFor('fullscreen')
export const $stage = symbolFor('stage')
export const $root = symbolFor('root')
export const $resource = symbolFor('resource')
export const $destroy = symbolFor('destroy')
export const $setActiveNode = symbolFor('setActiveNode')
export const $displayIndex = symbolFor('displayIndex')
export const $activeNode = symbolFor('activeNode')
export const $destroying = symbolFor('destroying')
export const $mainLoopHandle = symbolFor('mainLoopHandle')
export const $fps = symbolFor('fps')
export const $attach = symbolFor('attach')
export const $detach = symbolFor('detach')
export const $frame = symbolFor('frame')
export const $displays = symbolFor('displays')
export const $exitListener = symbolFor('exitListener')
export const $quitRequested = symbolFor('quitRequested')
export const $input = symbolFor('input')
export const $audio = symbolFor('audio')
export const $phase = symbolFor('phase')
export const $type = symbolFor('type')
export const $timestamp = symbolFor('timestamp')
export const $key = symbolFor('key')
export const $pressed = symbolFor('pressed')
export const $repeat = symbolFor('repeat')
export const $mapping = symbolFor('mapping')
export const $source = symbolFor('source')
export const $device = symbolFor('device')
export const $connected = symbolFor('connected')
export const $button = symbolFor('button')
export const $axis = symbolFor('axis')
export const $value = symbolFor('value')
export const $cancelled = symbolFor('cancelled')
export const $navigationManager = symbolFor('navigationManager')
export const $hasFocus = symbolFor('hasFocus')
export const $audioSourceMap = symbolFor('audioSourceMap')
export const $state = symbolFor('state')
export const $init = symbolFor('init')
export const $options = symbolFor('options')
export const $buffer = symbolFor('buffer')
export const $asyncId = symbolFor('asyncId')
export const $owner = symbolFor('owner')
export const $resourcePath = symbolFor('resourcePath')
export const $stream = symbolFor('stream')
export const $sample = symbolFor('sample')
export const $destination = symbolFor('destination')
