name: build-linux-x64

on:
  push:
    branches:
      - master

env:
  npm_config_lse_install_opts: --jobs max
  npm_config_lse_enable_native_tests: 1

jobs:
  build-linux-x64-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.6.0

      - name: Linux Packages
        uses: ./.github/actions/apt-get
        with:
          ppa: 'ubuntu-toolchain-r-test'
          packages: g++-6 gcc-6

      - name: Use GCC 6
        uses: ./.github/actions/use-gcc-6

      - name: Build
        run: yarn --force
        shell: bash

      - name: CPP Lint
        run: yarn run cpplint
        working-directory: packages/@lse/core
        shell: bash

      - name: JS Test (+ JS Lint)
        run: yarn run test
        shell: bash
