name: lse-runtime-packages

on: workflow_dispatch

env:
  npm_config_lse_install_opts: --jobs max
  npm_config_lse_enable_native_tests: 0
  CI_URL: https://github.com/lightsourceengine/ci/releases/download/v1.0.0

defaults:
  run:
    shell: bash

jobs:
  build-lse-runtime-linux-x64-job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.0.0

      - name: Linux Packages
        uses: ./.github/actions/apt-get
        with:
          ppa: 'ubuntu-toolchain-r-test'
          packages: g++-8 gcc-8

      - name: Use GCC 8
        uses: ./.github/actions/use-gcc-8

      - name: Install UPX
        uses: ./.github/actions/install-upx

      - name: Prepare scripts
        run: yarn
        working-directory: scripts

      - name: Create Runtime Package
        run: ./lse-runtime-build.js --recipe recipe://linux-x64
        working-directory: scripts

      - name: Create AppImage
        run: ./create-appimage.sh x64 ../build/LightSourceEngine-x64.ai ../build/LightSourceEngine-x64.AppImage
        working-directory: scripts

      - name: Upload Runtime Package
        uses: actions/upload-artifact@v2
        with:
          name: lse-runtime-desktop-artifact
          if-no-files-found: error
          retention-days: 3
          path: build/LightSourceEngine-*.AppImage

  build-lse-runtime-linux-arm64-job:
    runs-on: ubuntu-18.04
    env:
      CROSS_TOOLCHAIN_VERSION: 8
      CROSS_TOOLCHAIN_PREFIX: aarch64-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: srcroot
          submodules: recursive

      - name: Checkout ci
        uses: actions/checkout@v2
        with:
          repository: lightsourceengine/ci
          path: ci

      - name: Install UPX
        uses: ./srcroot/.github/actions/install-upx

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.0.0

      - name: Linux Packages
        uses: ./srcroot/.github/actions/apt-get
        with:
          packages: g++-8-aarch64-linux-gnu

      - name: Create Runtime Package
        run: |
          export PATH="${{github.workspace}}/ci/bin:${PATH}"
          yarn
          ./lse-runtime-build.js --recipe recipe://linux-arm64
        working-directory: srcroot/scripts

      - name: Create AppImage
        run: ./create-appimage.sh arm64 ../build/LightSourceEngine-arm64.ai ../build/LightSourceEngine-arm64.AppImage
        working-directory: srcroot/scripts

      - name: Upload Runtime Package
        uses: actions/upload-artifact@v2
        with:
          name: lse-runtime-desktop-artifact
          if-no-files-found: error
          retention-days: 3
          path: srcroot/build/LightSourceEngine-*.AppImage

  build-lse-runtime-mac-x64-job:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: srcroot
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.0.0

      - name: Install UPX
        uses: ./srcroot/.github/actions/install-upx

      - name: Create Runtime Package
        run: |
          yarn
          ./lse-runtime-build.js --recipe recipe://macos-x64
        working-directory: srcroot/scripts

      - name: Upload Runtime Package
        uses: actions/upload-artifact@v2
        with:
          name: lse-runtime-desktop-artifact
          if-no-files-found: error
          retention-days: 3
          path: srcroot/build/LightSourceEngine-*.tgz

  build-lse-runtime-win-x64-job:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: srcroot
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.0.0

      - name: Create Runtime Package
        run: |
          yarn
          ./lse-runtime-build.js --recipe recipe://windows-x64
        working-directory: srcroot/scripts

      - name: Upload Runtime Package
        uses: actions/upload-artifact@v2
        with:
          name: lse-runtime-desktop-artifact
          if-no-files-found: error
          retention-days: 3
          path: srcroot/build/LightSourceEngine-*.zip

  build-lse-runtime-linux-arm-job:
    runs-on: ubuntu-18.04
    env:
      CROSS_TOOLCHAIN_PREFIX: arm-rpi-linux-gnueabihf
    strategy:
      matrix:
        include:
          - recipe: linux-armv6l
            artifact: lse-runtime-desktop-artifact
            arch: armv6l
          - recipe: linux-armv7l
            artifact: lse-runtime-desktop-artifact
            arch: armv7l
          - recipe: nclassic
            artifact: lse-runtime-board-artifact
          - recipe: pi-armv6l
            artifact: lse-runtime-board-artifact
          - recipe: pi-armv7l
            artifact: lse-runtime-board-artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: srcroot
          submodules: recursive

      - name: Get ARM Toolchain
        run: |
          wget ${CI_URL}/x64-gcc-8.3.0.tar.xz
          tar -xJf x64-gcc-8.3.0.tar.xz
          echo "${{github.workspace}}/x64-gcc-8.3.0/arm-rpi-linux-gnueabihf/bin" >> $GITHUB_PATH

      - name: Install UPX
        uses: ./srcroot/.github/actions/install-upx

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.0.0

      - name: Create Runtime Package
        run: |
          yarn
          ./lse-runtime-build.js --recipe recipe://${{ matrix.recipe }}
          if [ -d "../build/LightSourceEngine-${{ matrix.arch }}.ai" ]; then ./create-appimage.sh ${{ matrix.arch }} ../build/LightSourceEngine-${{ matrix.arch }}.ai ../build/LightSourceEngine-${{ matrix.arch }}.AppImage; fi
        working-directory: srcroot/scripts

      - name: Upload Runtime Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          if-no-files-found: error
          retention-days: 3
          path: |
            srcroot/build/LightSourceEngine-*.tgz
            srcroot/build/LightSourceEngine-*.AppImage
            srcroot/build/LightSourceEngine-*.hmod
