name: lse-runtime-packages

on: workflow_dispatch

env:
  npm_config_lse_install_opts: --jobs max
  npm_config_lse_enable_native_tests: 0
  CI_URL: https://github.com/lightsourceengine/ci/releases/download/v1.1.0/

defaults:
  run:
    shell: bash

jobs:
  build-lse-runtime:
    strategy:
      fail-fast: false
      matrix:
        include:
          # primary desktop builds
          - host: windows-2019
            platform: windows
            arch: x64
            artifact: desktop
          - host: macos-10.15
            platform: macos
            arch: x64
            artifact: desktop
          - host: ubuntu-18.04
            platform: linux
            arch: x64
            gcc: 8
            artifact: desktop
          # linux arm builds
          - host: ubuntu-18.04
            platform: linux
            arch: arm64
            gcc: 8
            artifact: linux-arm
          - host: ubuntu-18.04
            platform: linux
            arch: armv6l
            gcc: 8.3.0
            artifact: linux-arm
          - host: ubuntu-18.04
            platform: linux
            arch: armv7l
            gcc: 8.3.0
            artifact: linux-arm
          # board specific builds
          - host: ubuntu-18.04
            platform: nclassic
            arch: armv7l
            gcc: 6.5.0
            artifact: board
          - host: ubuntu-18.04
            platform: pi
            arch: armv6l
            gcc: 8.3.0
            artifact: board
          - host: ubuntu-18.04
            platform: pi
            arch: armv7l
            gcc: 8.3.0
            artifact: board

    name: ${{ format('lse-runtime-{0}-{1}', matrix.platform, matrix.arch) }}

    runs-on: ${{ matrix.host }}

    steps:
      - name: Checkout LightSourceEngine
        uses: actions/checkout@v2
        with:
          path: srcroot
          submodules: recursive

      - name: Checkout ci
        if: contains(matrix.arch, 'arm64')
        uses: actions/checkout@v2
        with:
          repository: lightsourceengine/ci
          path: ci

      - name: Set ci Path
        if: contains(matrix.arch, 'arm64')
        run: echo "${{ github.workspace }}/ci/bin" >> $GITHUB_PATH

      - name: Install Node 15
        if: contains(matrix.platform, 'nclassic')
        uses: actions/setup-node@v1
        with:
          node-version: 15.6.0

      - name: Install Node 16
        if: contains(matrix.platform, 'nclassic') == false
        uses: actions/setup-node@v1
        with:
          node-version: 16.0.0

      - name: Install GCC Toolchain
        if: startsWith(matrix.host, 'ubuntu')
        uses: ./srcroot/.github/actions/gcc-toolchain
        with:
          arch: ${{ matrix.arch }}
          version: ${{ matrix.gcc }}

      - name: Install UPX
        if: startsWith(matrix.host, 'ubuntu') || startsWith(matrix.host, 'macos')
        uses: ./srcroot/.github/actions/install-upx

      - name: Prepare scripts
        run: yarn
        working-directory: srcroot/scripts

      - name: Create Runtime Package
        run: ./lse-runtime-build.js --recipe recipe://${{ matrix.platform }}-${{ matrix.arch }}
        working-directory: srcroot/scripts

      - name: Create AppImage
        if: startsWith(matrix.host, 'ubuntu')
        run: |
          if [ -d "../build/LightSourceEngine-${{ matrix.arch }}.AppDir" ]; then
            ./create-appimage.sh ${{ matrix.arch }} ../build/LightSourceEngine-${{ matrix.arch }}.AppDir ../build/LightSourceEngine-${{ matrix.arch }}.AppImage
          fi
        working-directory: srcroot/scripts

      - name: Upload Runtime Package
        uses: actions/upload-artifact@v2
        with:
          name: lse-runtime-${{ matrix.artifact }}-artifact
          if-no-files-found: error
          retention-days: 3
          path: |
            srcroot/build/LightSourceEngine-*.tgz
            srcroot/build/LightSourceEngine-*.AppImage
            srcroot/build/LightSourceEngine-*.hmod
            srcroot/build/LightSourceEngine-*.zip
