name: lse-npm-packages

on: workflow_dispatch

env:
  npm_config_lse_install_opts: --jobs max

jobs:
  npm-packages-job:
    defaults:
      run:
        shell: bash
        working-directory: scripts
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]
        node: [15.0.0, 15.14.0]
        include:
          - os: ubuntu-18.04
            node: 15.14.0
            upload_artifacts: yes
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Linux Packages
        if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/apt-get
        with:
          ppa: 'ubuntu-toolchain-r-test'
          packages: g++-8 gcc-8

      - name: Use GCC 8
        if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/use-gcc-8

      - name: Install Scripts
        run: yarn

      - name: Create NPM Package Tarballs
        run: ./create-npm-packages.sh

      - name: Test Package Insall
        run: ./test-npm-packages-install.sh

      - name: Upload NPM Packages
        if: matrix.upload_artifacts == 'yes'
        uses: actions/upload-artifact@v2
        with:
          name: lse-npm-packages-artifact
          if-no-files-found: error
          retention-days: 3
          path: build/npm/publishable/*.tgz
