name: lse-build

on:
  push:
    branches:
      - master

env:
  npm_config_lse_install_opts: --jobs max
  npm_config_lse_enable_native_tests: 1

jobs:
  build-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-18.04, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.0.0

      - name: Install GCC8
        if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/gcc-toolchain
        with:
          arch: x64
          version: 8

      - name: Yarn Cache
        uses: egordm/gha-yarn-node-cache@v1

      - name: Build
        run: yarn --force

      - name: CPP Lint
        if: contains(matrix.os, 'windows') == false
        run: yarn run cpplint
        working-directory: packages/@lse/core

      - name: JS Test (+ JS Lint)
        run: yarn run test

      - name: Documentation
        run: yarn run jsdoc
  compatibility-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node-version: [14, 15, 16]
        gcc-version: [5, 6]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install GCC ${{ matrix.gcc-version }}
        uses: ./.github/actions/gcc-toolchain
        with:
          arch: x64
          version: ${{ matrix.gcc-version }}

      - name: Yarn Cache
        uses: egordm/gha-yarn-node-cache@v1

      - name: Build
        run: yarn --force

      - name: JS Test (+ JS Lint)
        run: yarn run test
