name: lse-npm-packages

on: workflow_dispatch

env:
  npm_config_lse_install_opts: --jobs max

jobs:
  npm-packages-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 15.6.0

      - name: Install Scripts
        shell: bash
        working-directory: scripts
        run: yarn

      - name: Create NPM Package Tarballs
        shell: bash
        working-directory: scripts
        run: ./create-npm-packages.sh

      - name: Upload NPM Packages
        uses: actions/upload-artifact@v2
        with:
          name: lse-npm-packages-artifact
          if-no-files-found: error
          retention-days: 3
          path: build/npm/publishable/*.tgz
